"""create expires fields in Subscription table

Revision ID: c37532e875e6
Revises:
Create Date: 2026-02-25 19:23:28.181555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c37532e875e6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("notified_3_days", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "subscriptions",
        sa.Column("notified_1_day", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "subscriptions",
        sa.Column("notified_expired", sa.Boolean(), nullable=False),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("subscriptions", "notified_expired")
    op.drop_column("subscriptions", "notified_1_day")
    op.drop_column("subscriptions", "notified_3_days")
    # ### end Alembic commands ###
